[package]
name = "osloader"
version = "0.1.0"
authors = ["VenmoSnake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
no-std=[]
std=[]

[dependencies.bitflags]
version = "1.0.4"

[dependencies.uefi]
version="0.4.0"